import type { SimpleIcon } from 'simple-icons'
import {
  siApachekafka,
  siApachemaven,
  siBun,
  siClojure,
  siCmake,
  siCplusplus,
  siDart,
  siDeno,
  siDocker,
  siDotnet,
  siElixir,
  siErlang,
  siFlutter,
  siGnubash,
  siGo,
  siGradle,
  siGnu,
  siHaskell,
  siJulia,
  siKotlin,
  siKubernetes,
  siLlvm,
  siMariadb,
  siMongodb,
  siMysql,
  siNginx,
  siNodedotjs,
  siOpenjdk,
  siPerl,
  siPhp,
  siPostgresql,
  siPython,
  siR,
  siRabbitmq,
  siRedis,
  siRuby,
  siRust,
  siScala,
  siSqlite,
  siSwift,
  siTerraform,
  siTypescript,
} from 'simple-icons'

export const DEPENDENCY_BRANDS: Record<string, SimpleIcon> = {
  java: siOpenjdk,
  python: siPython,
  nodejs: siNodedotjs,
  go: siGo,
  rust: siRust,
  dotnet: siDotnet,
  ruby: siRuby,
  php: siPhp,
  kotlin: siKotlin,
  swift: siSwift,
  typescript: siTypescript,
  cpp: siCplusplus,
  scala: siScala,
  elixir: siElixir,
  deno: siDeno,
  bun: siBun,
  clojure: siClojure,
  haskell: siHaskell,
  perl: siPerl,
  rlang: siR,
  julia: siJulia,
  erlang: siErlang,
  dart: siDart,
  flutter: siFlutter,
  docker: siDocker,
  kubernetes: siKubernetes,
  postgres: siPostgresql,
  redis: siRedis,
  mongo: siMongodb,
  mysql: siMysql,
  mariadb: siMariadb,
  sqlite: siSqlite,
  rabbitmq: siRabbitmq,
  kafka: siApachekafka,
  nginx: siNginx,
  terraform: siTerraform,
  gnu: siGnu,
  llvm: siLlvm,
  cmake: siCmake,
  bash: siGnubash,
  gradle: siGradle,
  maven: siApachemaven,
}

export function getDependencyBrandIcon(brand: string): SimpleIcon | undefined {
  return DEPENDENCY_BRANDS[brand]
}
